CREATE DATABASE IF NOT EXISTS db2019 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON db2019.* TO 'root'@'%' IDENTIFIED BY '123456' WITH GRANT OPTION;
GRANT FILE ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;

CREATE TABLE `payment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `serial` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;